development:
  adapter: mysql2
  database: movies_api_dev
  pool: 5
  timeout: 5000
  username: root
  password:

test:
  adapter: mysql2
  database: movies_api_test
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: mysql2
  database: movies_api_pro
  pool: 5
  timeout: 5000
